# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: true

# Setup
title: Tiny Mighty Blog
tagline: The Tiny (but mighty) Personal Blog of Jess Jones
url: http://www.tinymightyblog.com
paginate: 1
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Jess Jones
  url: https://twitter.com/jjessjjones
  email: jjessjjones@gmail.com

# Custom vars
version: 1.0.0

prose:
  rooturl: '_posts'
  siteurl: 'http://www.tinymightyblog.com'
  media: 'assets/images/posts'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field: 
          element: "select"
          label: "Category"
          help: "select a category from the list."
          options: 
            - name: "Style"
              value: "style"
            - name: "DIY"
              value: "diy"
            - name: "Travel"
              value: "travel"
            - name: "Baking"
              value: "baking"
            - name: "Atlanta"
              value: "atlanta"
            - name: "Music"
              value: "music"
      - name: "tags"
        field:
          element: "multiselect"
          alterable: "true"
          label: "tags"
          placeholder: "add tags"
