# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: true

# Setup
title: Tiny Mighty Blog
tagline: The Tiny (but mighty) Personal Blog of Jess Jones
url: http://www.tinymightyblog.com
paginate: 1
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Jess Jones
  url: https://twitter.com/jjessjjones
  email: jjessjjones@gmail.com

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/jjessjjones/tinymightyblog

prose:
  rooturl: '_posts'
